##################################
#     Spring configurations      #
##################################
spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/fleet_manager}
    username: ${JDBC_DATABASE_USERNAME:fleet_manager}
    password: ${JDBC_DATABASE_PASSWORD:fleet_manager}
  dbcp2:
    max-wait-millis: 30000
    validation-query: "SELECT 1"
    validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            '[non_contextual_creation]': true
        id:
          '[new_generator_mappings]': true
  thymeleaf:
    cache: false
springdoc:
  pathsToMatch: /api/**

##################################
#     Server configurations      #
##################################
server:
  # address: 0.0.0.0
  port: 8090 
